controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_to_DOF1
      - joint_to_Arm1
      - joint_to_Arm2
      - joint_to_Arm3
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: rest_possition