#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
  - joint_to_DOF1
  - joint_to_Arm1
  - joint_to_Arm2
  - joint_to_Arm3

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50