#This is a movit contoller connecting follow_joint_trajectory controller with JointTrajectoryController

controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - joint_to_DOF1
    - joint_to_Arm1
    - joint_to_Arm2
    - joint_to_Arm3